// <auto-generated />
using System;
using Book.Api.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Book.Api.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20250208163147_v1_0_0_BookMigration")]
    partial class v1_0_0_BookMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Book.Api.Saga.BookingSagaData", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BookingFinished")
                        .HasColumnType("boolean");

                    b.Property<string>("CarPlateNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CarRented")
                        .HasColumnType("boolean");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("FlightBooked")
                        .HasColumnType("boolean");

                    b.Property<string>("FlightCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HotelBooked")
                        .HasColumnType("boolean");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TravelerId")
                        .HasColumnType("uuid");

                    b.HasKey("CorrelationId");

                    b.ToTable("BookingSagaData");
                });
#pragma warning restore 612, 618
        }
    }
}
